name: "CI/CD workflow: Build and Deploy"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: kingfisher
    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install requirements
        run: pip install --no-cache-dir -r requirements.txt
          
  deploy:
    runs-on: kingfisher
    needs: build
    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Symlink actions repository
        run: |
          [ -d "$HOME/kingfisher" ] || ln -s "$PWD" "$HOME/kingfisher"

      - name: Set up virtual environment
        run: mkdir -p venv

      - name: Symlink python lib to venv/lib
        run: |
          [ -L venv/lib ] || ln -s "$(find $(realpath $PWD)/../../_tool -type d -name "lib" | head -n 1)" venv/

      - name: Symlink python path to venv/bin
        run: |
          [ -L venv/bin ] || ln -s "$(find $(realpath $PWD)/../../_tool -type d -name "bin" | head -n 1)" venv/

      - name: Restart kingfisher.service
        run: sudo systemctl restart kingfisher.service
